# Workflow for implementing CI using Actions

name: CI

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Specifies which OS to run on
    runs-on: macos-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v3

      # Creates Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pytest
          # Install requirements.txt if it exists
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs flake8 to check for errors
      - name: Lint with flake8
        run: flake8
        
      # Runs pytest
      - name: Test with pytest
        run: pytest
